In [ ]:
import pandas as pd
import random

fake = Faker()

rows = []
months = ['202601','202602','202603']

In [43]:

rows = []
months = ['202601','202602','202603']
# hierarchy rule
HIERARCHY = {
    "KORPORASI":1,
    "SME": 2,
    "MIKRO": 3,
    "KONSUMER": 4
}
acct_global = set()
acct_map = {}  # ensures acctno belongs to only 1 CIF

for i in range(50):  # CIF
    cif = f"CIF{i:04d}"

        # STEP 1: decide CIF-level flag FIRST
    cif_flag = random.choice([0, 1])

    # apply override rule
    if cif_flag == 1:
        final_flag = -1
    else:
        final_flag = 0

    num_accounts = random.randint(1, 3)
    accounts = []

    for _ in range(num_accounts):

        # UNIQUE acctno
        while True:
            acctno = random.randint(100000, 999999)
            if acctno not in acct_global:
                acct_global.add(acctno)
                break

        segmen = random.choice(list(HIERARCHY.keys()))

        accounts.append({
            "acctno": acctno,
            "segmen": segmen
        })

        acct_map[acctno] = cif  # FIX: enforce 1 acct → 1 CIF

    segmentasi_cif = max(accounts, key=lambda x: HIERARCHY[x["segmen"]])["segmen"]

    for acc in accounts:
        acctno = acc["acctno"]

        for ds in months:
            num_features = random.randint(1, 3)

            for _ in range(num_features):

                rows.append({
                    "ds": ds,

                    # FIXED RELATIONSHIP
                    "acctno": acctno,
                    "cifno": cif,

                    "segmen": acc["segmen"],
                    "segmentasi_cif": segmentasi_cif,

                    "jenis_simpanan": random.choice(["GIRO","BRITAMA BISNIS"]),
                    "open_date": fake.date_between(start_date="-2y", end_date="-6M"),

                    "flag_qlola_cif": random.randint(0,1),
                    "ro": random.choice(["RO1","RO2","RO3"]),

                    "group_pengelola": random.choice(["DIVABC","DIVDEF"]),
                    "status": "active",

                    "endbal": random.randint(1_000_000, 10_000_000),
                    "ratas_saldo": random.randint(1_000_000, 10_000_000) * 0.9,

                    "featuredesc": random.choice([
                        "BI FAST",
                        "FUND TRANSFER",
                        "RTGS",
                        "KLIRING"
                    ]),

                    "kode_cabang": random.randint(10000,99999),
                    "nama_cabang": random.choice(["KC Ampera","KC Radio Dalam","KC Menara Brilian"]),

                    "freq_qlola": random.randint(0,10),
                    "sv_qlola": random.randint(10000,500000),
                    "fbi_qlola": random.randint(1000,10000)
                })

df = pd.DataFrame(rows)

In [44]:
df.head()

,ds,acctno,cifno,segmen,segmentasi_cif,jenis_simpanan,open_date,flag_qlola_cif,ro,group_pengelola,status,endbal,ratas_saldo,featuredesc,kode_cabang,nama_cabang,freq_qlola,sv_qlola,fbi_qlola
0,202601,942387,CIF0000,MIKRO,MIKRO,GIRO,2025-08-20,0,RO3,DIVABC,active,9809233,8666787.6,FUND TRANSFER,93930,KC Ampera,10,117646,1630
1,202601,942387,CIF0000,MIKRO,MIKRO,BRITAMA BISNIS,2024-11-02,0,RO2,DIVDEF,active,7437809,4776825.6,BI FAST,10923,KC Radio Dalam,4,381026,6890
2,202602,942387,CIF0000,MIKRO,MIKRO,BRITAMA BISNIS,2024-05-08,1,RO1,DIVDEF,active,7040489,6928248.6,KLIRING,86917,KC Ampera,1,289554,2997
3,202602,942387,CIF0000,MIKRO,MIKRO,BRITAMA BISNIS,2024-09-29,1,RO2,DIVDEF,active,9324038,2077516.8,KLIRING,11684,KC Menara Brilian,4,143987,6900
4,202602,942387,CIF0000,MIKRO,MIKRO,GIRO,2024-10-01,0,RO2,DIVDEF,active,9511392,2121166.8,FUND TRANSFER,50613,KC Radio Dalam,1,292647,5556

In [46]:
cifno=list(df.cifno.unique())

In [48]:
cif_map={key: random.randint(0, 1) for key in cifno}

In [50]:
df['flag_qlola_cif']=df['cifno'].map(cif_map)

In [51]:
df.head()

,ds,acctno,cifno,segmen,segmentasi_cif,jenis_simpanan,open_date,flag_qlola_cif,ro,group_pengelola,status,endbal,ratas_saldo,featuredesc,kode_cabang,nama_cabang,freq_qlola,sv_qlola,fbi_qlola
0,202601,942387,CIF0000,MIKRO,MIKRO,GIRO,2025-08-20,1,RO3,DIVABC,active,9809233,8666787.6,FUND TRANSFER,93930,KC Ampera,10,117646,1630
1,202601,942387,CIF0000,MIKRO,MIKRO,BRITAMA BISNIS,2024-11-02,1,RO2,DIVDEF,active,7437809,4776825.6,BI FAST,10923,KC Radio Dalam,4,381026,6890
2,202602,942387,CIF0000,MIKRO,MIKRO,BRITAMA BISNIS,2024-05-08,1,RO1,DIVDEF,active,7040489,6928248.6,KLIRING,86917,KC Ampera,1,289554,2997
3,202602,942387,CIF0000,MIKRO,MIKRO,BRITAMA BISNIS,2024-09-29,1,RO2,DIVDEF,active,9324038,2077516.8,KLIRING,11684,KC Menara Brilian,4,143987,6900
4,202602,942387,CIF0000,MIKRO,MIKRO,GIRO,2024-10-01,1,RO2,DIVDEF,active,9511392,2121166.8,FUND TRANSFER,50613,KC Radio Dalam,1,292647,5556

In [52]:
from sqlalchemy import create_engine

In [53]:
engine = create_engine("postgresql://postgres:admins@localhost/ragdb")

In [55]:
df.to_sql("master_qlola", engine, if_exists="append", index=False)

589

In [56]:
acct_list = df["acctno"].dropna().unique().tolist()
ds_list = ["202601", "202602", "202603"]

# limit total rows
n = min(300, len(acct_list) * 5)  # flexible but capped at 300

jenis_trx_list = ["BI FAST", "FUND TRANSFER", "RTGS", "KLIRING"]

data = []

for i in range(n):
    data.append({
        "ds": random.choice(ds_list),
        "acctno": random.choice(acct_list),
        "jenis_trx": random.choice(jenis_trx_list),
        "freq_trx": random.randint(1, 20),
        "sv_trx": round(random.uniform(10000, 5000000), 2)
    })

df_txn = pd.DataFrame(data)

In [59]:
df_txn.to_sql("transaction_non_qlola", engine, if_exists="append", index=False)

300

In [60]:
df.columns

Index(['ds', 'acctno', 'cifno', 'segmen', 'segmentasi_cif', 'jenis_simpanan',
       'open_date', 'flag_qlola_cif', 'ro', 'group_pengelola', 'status',
       'endbal', 'ratas_saldo', 'featuredesc', 'kode_cabang', 'nama_cabang',
       'freq_qlola', 'sv_qlola', 'fbi_qlola'],
      dtype='object')

In [61]:
df.head()

,ds,acctno,cifno,segmen,segmentasi_cif,jenis_simpanan,open_date,flag_qlola_cif,ro,group_pengelola,status,endbal,ratas_saldo,featuredesc,kode_cabang,nama_cabang,freq_qlola,sv_qlola,fbi_qlola
0,202601,942387,CIF0000,MIKRO,MIKRO,GIRO,2025-08-20,1,RO3,DIVABC,active,9809233,8666787.6,FUND TRANSFER,93930,KC Ampera,10,117646,1630
1,202601,942387,CIF0000,MIKRO,MIKRO,BRITAMA BISNIS,2024-11-02,1,RO2,DIVDEF,active,7437809,4776825.6,BI FAST,10923,KC Radio Dalam,4,381026,6890
2,202602,942387,CIF0000,MIKRO,MIKRO,BRITAMA BISNIS,2024-05-08,1,RO1,DIVDEF,active,7040489,6928248.6,KLIRING,86917,KC Ampera,1,289554,2997
3,202602,942387,CIF0000,MIKRO,MIKRO,BRITAMA BISNIS,2024-09-29,1,RO2,DIVDEF,active,9324038,2077516.8,KLIRING,11684,KC Menara Brilian,4,143987,6900
4,202602,942387,CIF0000,MIKRO,MIKRO,GIRO,2024-10-01,1,RO2,DIVDEF,active,9511392,2121166.8,FUND TRANSFER,50613,KC Radio Dalam,1,292647,5556

In [62]:
df_txn.head()

       ds  acctno      jenis_trx  freq_trx      sv_trx
0  202603  405962        KLIRING        10   326947.04
1  202601  942387  FUND TRANSFER         1  4959964.96
2  202601  146444        KLIRING        17  1374501.53
3  202601  392265        KLIRING         1   228667.91
4  202602  734294           RTGS        18  3425974.64

In [70]:
engine = create_engine(
    "postgresql+psycopg2://postgres.klybchbbtjrsompshgbc:supabaseunited10@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres",
    connect_args={"sslmode": "require"}
)

In [1]:
engine = create_engine(os.getenv("SUPABASE_DB_URL"))

NameError: name 'create_engine' is not defined

In [71]:
df.to_sql(
    "master_qlola",
    engine,
    if_exists="append",
    index=False,
    method="multi",
    chunksize=1000
)

df_txn.to_sql(
    "transaction_non_qlola",
    engine,
    if_exists="append",
    index=False,
    method="multi",
    chunksize=1000
)

300

In [72]:
pd.read_sql("select count(*) from master_qlola", engine)

   count
0    589

In [73]:
pd.read_sql("select count(*) from transaction_non_qlola", engine)

   count
0    300